### PR TITLE
Feature/client edit

### PR DESCRIPTION
**Pull request by wilsoncooked**

### CODE REVIEW

**Comment by jenna1k** [comment]
I have this when I click `New Client` button :beetle:

**Review by jenna1k — APPROVED** [review]

**Comment by wilsoncooked** [comment]
Just saw that the PUT method isn't working with Heroku as it was with my localhost so will check and fix tomorrow

**Comment by wilsoncooked** [comment]
The PUT method works now! Yay please check and approve if good

**Review by aliashkevich — APPROVED** [review]
Good job :)

**Pull request merged**
